<?php

namespace Planck\View\Component\EntityEditor\Form\Renderer;


use Phi\HTML\ViewComponent;
use Planck\Model\Entity;

class None extends Text
{


    public function render()
    {

        return '';


        //return parent::render(); // TODO: Change the autogenerated stub
    }

}
