<?php

namespace Planck\Extension\EntityEditor\View\Component\Form\Renderer;


use Planck\Model\Entity;
use Planck\View\Component;

class Text extends Component
{

    /**
     * @var Entity
     */
    protected $entity;

    protected $descriptor;

    protected $fieldName;

    protected $defaultDescriptor = array(
        'label' => ''
    );



    public function __construct($fieldName, $descriptor, Entity $entity)
    {

        parent::__construct();

        $this->fieldName = $fieldName;
        $this->entity = $entity;
        $this->descriptor = array_merge($this->defaultDescriptor, $descriptor);

        $this->setVariable('entity', $entity);

    }


    public function render()
    {

        $readonly = '';
        if(isset($this->descriptor['readonly']) && $this->descriptor['readonly']) {
            $readonly = ' readonly';
        }

        return '
            <div class="md-input-wrapper plk-field-container">
                <input type="text" class="form-data md-form-control md-static '.$readonly.'" name="'.$this->fieldName.'" value=""/>
                <label>'.$this->descriptor['label'].'</label>
                <span class="md-line"></span>
            </div>
        ';



        //return parent::render(); // TODO: Change the autogenerated stub
    }

}
